from sqlalchemy import select, update, delete
from sqlalchemy.ext.asyncio import AsyncSession
from models import Words

class WordsRepository:
    async def create(session: AsyncSession):
        ...
    async def get_by_id(session: AsyncSession):
        ...
    async def get_all(session: AsyncSession):
        ...
    async def remove(session: AsyncSession):
        ...
    async def update(session: AsyncSession):
        ...